### ISSUE TITLE
Better JSON parsing error messages

### ISSUE THREAD

**Issue by mhkeller** [dmnsgn/gulp-json-stylus#1]
If this [JSON.parse](https://github.com/dmnsgn/gulp-json-stylus/blob/04b644cf93f1d6365a04df2b20b6975dc4afee93/index.js#L54) fails, it will throw an error that might be hard to debug for some people. I got to this scenario since I had left some comments in the file after converting it from a javascript object literal.

Some options
- Use the `isJSON.strict` within the conditional which will use a try/catch before parsing
- Use the [parse-json](https://www.npmjs.com/package/parse-json) library, which has more descriptive errors

**Comment by dmnsgn** [comment]
I have opted for parse-json. See b4247006f986df8a1e2c60289e3f91293a7a1ec1 . Feel free to reopen/PR if not what you had in mind. Thanks.

**Comment by mhkeller** [comment]
👍🏼
